---
title: "Assignment8_BosFloodClaims"
author: "Megan Willis-Jackson"
date: "11/4/2021"
output: html_document
---

```{r libraries}
library(sf)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggspatial)



```


```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

bfloodclaims <- read.csv("C:/Users/mwill/OneDrive - Harvard University/2021 - Fall/Mapping Urbanization/Assignments/Assignment8/Data/suffolk_tract_counts.csv")

bos_tracts <- st_read("C:/Users/mwill/OneDrive - Harvard University/2021 - Fall/Mapping Urbanization/Assignments/Assignment8/AllBostonTract")

bos_zip <- st_read("C:/Users/mwill/OneDrive - Harvard University/2021 - Fall/Mapping Urbanization/Assignments/Assignment8/bos_zip")

nfip_zip <- read.csv("C:/Users/mwill/OneDrive - Harvard University/2021 - Fall/Mapping Urbanization/Assignments/Assignment8/pct_increase_policy.csv")

policy_increase <- nfip_zip %>%
  left_join(bos_zip, by = c("zip_txt" = "GEOID20")) %>%
  st_as_sf() %>%
  st_transform(MA_state_plane)

bos_claims <- bfloodclaims %>%
  left_join(bos_tracts, by = c("censusTract" = "GEOID2")) %>%
  filter(claim_count > 0) %>%
  st_as_sf() %>%
  st_transform(MA_state_plane)

st_write(bos_claims, "C:/Users/mwill/OneDrive - Harvard University/2021 - Fall/Mapping Urbanization/Assignments/Assignment8/Data/bos_claims/bos_claims.shp")

st_write(policy_increase, "C:/Users/mwill/OneDrive - Harvard University/2021 - Fall/Mapping Urbanization/Assignments/Assignment8/Data/zip_increase/zip_increase.shp")

```


```{r}
right_side <- st_bbox(bos_claims)$xmax
left_side  <- st_bbox(bos_claims)$xmin
top_side <- st_bbox(bos_claims)$ymax
bottom_side <- st_bbox(bos_claims)$ymin


ggplot(bos_claims) +
  geom_sf(data = policy_increase %>% filter(PercentIncrease > 0),
          aes(fill = PercentIncrease), 
          color = NA, alpha = .5) +
  geom_sf(aes(fill = claims_paidout/claim_count), alpha = .9, color = NA)  +
  scale_fill_gradientn(name = "Amount per Claim", colours = c("seagreen", "red")) +
  geom_sf(data = st_centroid(bos_claims),
          aes(color = MedianInc)) +
  coord_sf(xlim = c(left_side, right_side),
           ylim = c(bottom_side, top_side)) +
  scale_color_viridis_c() +
  theme(legend.background = element_rect(fill = alpha("white", .5)))

ggplot(policy_increase) +
  geom_sf(aes(fill = PercentIncrease * 100), color = NA) +
  coord_sf(xlim = c(left_side, right_side),
           ylim = c(bottom_side, top_side))



```

```{r}
tract_claims <- summarise(bos_claims)


```











